import { NavMain } from '@/admin/NavMain'


export const metadata = {
  title: "Pagina para administracion",
  description: "Generated by create next app",
}

export default function AdminLayout({ children }) {
  return (



    <main className="container mx-auto  py-2 px-6 flex-grow">
      <NavMain></NavMain>
      {children}
    </main>


  )
}
